global:
  scrape_interval: 15s

scrape_configs:

- job_name: prometheus-api-cursos
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - prometheus-api-cursos:9090

- job_name: api-cursos
  metrics_path: /actuator/prometheus
  static_configs:
  - targets:
    - api-cursos:8080

- job_name: 'opentelemetry-collector'
  scrape_interval: 10s
  static_configs:
    - targets: ['opentelemetry-collector-api-cursos:8889']
    - targets: ['opentelemetry-collector-api-cursos:8888']

- job_name: 'jaeger'
  static_configs:
    - targets: ['jaeger-api-cursos:14269']
